stats: #
  75a25793-efc5-4a2e-a1ce-bb094d5ffcf4: "0/4/0/0/0/0/0"
blockedit: "§b方块皮肤"
sandstoneedit: "§b分类: 沙石"
wooledit: "§b分类: 羊毛"
oreblockedit: "§b分类: Ore (Blocks)"
oreedit: "§b分类: Ores"
quartzedit: "§b分类: Quartz Blocks"
woodedit: "§b分类: Woods"
clayedit: "§b分类: Clay"
resetconfirm: "§c你确定要重置吗?"
breaktool: "§6挖方块工具"
nv: "§a开关模式"
settings: "§c设置"
reset: "§c在当前模式下重置个人最佳"
category: "§e单击查看类别!"
blocks:
  - Sandstone Blocks
  - Wool Blocks
  - Ore (Blocks)
  - Ores
  - Quartz Blocks
  - Woods
  - Clay
yes: "§a确认"
no: "§c取消"
NoEnoughServers: '&c没有足够的服务器!'
UnSavedSettings: '&c放弃库存设置.'
MessageFormat: '%text% &8 &bb %text2%'
selected: '&a选择!'
SavedSettings: '&a保存设置.'
typename:
  - '&b普通'
  - '&b短的'
  - '&b斜的'
  - '&bOneStack'
  - '&b短斜的'
MenuTitle: '&bFastBuilder菜单'
Settings: '&c设置'
min: '&c最小值为1'
max: '&c最大值为20'
FallDelayLore:
  - '§b重生延迟'
  - ''
  - '§d当前: §e%int%§d 个方块'
  - '§a左键: §8 , §c右键: \u2191'
  - ''
  - '§c默认: 5'
Scoreboard:
  title: '§bFastBuilder'
  lines:
    - '§0'
    - '§1§8========= §e'
    - '§a%data%'
    - '§3'
    - '§6§f%first%'
    - '§5§f%second%'
    - '§4§f%third%'
    - '§3§r'
    - '§a§l最短时间:'
    - '§8%small%'
    - '§2§8'
    - '§b§l当前时间:'
    - '§f%time%'
    - ''
    - '§3LanternMC'
nomapsavaliable : '§7[§bFastBuilder§7] §c我们找不到任何可用的位置'
cancelled : '§7[§bFastBuilder§7] §c桥接尝试已取消! (超时)'